//
// Created by ronald on 21-12-15.
//

#ifndef MACHIAVELLI_BUILDINGTYPE_H
#define MACHIAVELLI_BUILDINGTYPE_H

enum class BuildingType {
    ESTATE,
    CHATEAU,
    PALACE,
    TAVERN,
    MARKET,
    STORES,
    COMMERCE_CENTER,
    DOCK,
    TOWN_HALL,
    TEMPLE,
    CHURCH, MONASTERY,
    CATHEDRAL,
    WATCH_TOWER,
    PRISON,
    TOURNAMENT_FIELD,
    CASTLE,
    COURTYARD_OF_WONDERS,
    DUNGEON,
    CEMETERY,
    LABORATORY,
    WORKSHOP,
    OBSERVATORY,
    LIBRARY,
    MAGICIANS_SCHOOL,
    DRAGON_GATE, UNIVERSITY
};

#endif //MACHIAVELLI_BUILDINGTYPE_H
