//
// Created by ronald on 21-12-15.
//

#ifndef MACHIAVELLI_CHARACTERTYPES_H
#define MACHIAVELLI_CHARACTERTYPES_H

enum class CharacterType {
    ASSASSIN, THIEF, MAGICIAN, KING, PREACHER, MERCHANT, BUILDER, CONDOTTIERI, INVALID
};

#endif //MACHIAVELLI_CHARACTERTYPES_H
